default_stages: [commit, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
        # https://github.com/pre-commit/pre-commit-hooks/issues/273
        # Not the best option but it doesn't seem to accept an 'ignore' option
        args: [--unsafe]
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: no-commit-to-branch
        args: ['--branch', 'master', '--branch', 'main']

  # NOTE: While commitizen provides "cz check" for validating commits against its 'schema_pattern' regex
  # it won't give you any detailed info on what exactly caused the validation to fail. It is for
  # that reason the prefer to use 'gitlint' instead of 'cz check' for commit message validation
  #
  # Requires that 'gitlint' is already installed (see Pipfile)
  # gitlint config file is .gitlint
  # Requires explicit installation with 'pre-commit install --hook-type commit-msg'
  # Refer to pre-commit documentation
  - repo: https://github.com/jorisroovers/gitlint
    rev:  v0.17.0
    hooks:
      - id: gitlint

  - repo: local
    hooks:
      - id: test
        name: Test
        entry: make
        args: ['test']
        pass_filenames: false
        language: system
