---
# Branches from where releases can happen
branches:
  - main
  - master

# Print additional info
debug: true

# Use 'conventionalcommits' preset instead of the default 'angular'
# this will passed down to all plugins
preset: conventionalcommits

# List of plugins to use.
# Since this project is an Ansible role we won't use the npm plugin.
# Since I'm not insterested in having a dedicated CHANGELOG.md file,
# I won't be using the 'changelog' plugin to create one nor the 'git'
# plugin to commit the generated 'CHANGELOG.md' back to git
plugins:

  # Analyze that commits conform to the preset specification
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: docs
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: revert
          release: patch
        - type: chore
          release: false
        - type: build
          release: false
        - type: ci
          release: false
        - type: test
          release: false
        - type: style
          release: false
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING

  # Generate release notes. These will be embedded in the Github release body
  - - "@semantic-release/release-notes-generator"
    - presetConfig:
        types:
          - type: feat
            section: ':sparkles: Features'
          - type: fix
            section: ':bug: Bug Fixes'
          - type: docs
            section: ':eyes: Misc'
          - type: chore
            section: ':eyes: Misc'
          - type: perf
            section: ':muscle: Improvements'
          - type: refactor
            section: ':muscle: Improvements'
          - type: style
            section: ':muscle: Improvements'
          - type: ci
            section: ':robot: Automation'
          - type: build
            section: ':robot: Automation'
          - type: test
            section: ':robot: Automation'
          - type: revert
            section: ':poop: Revert'
      writerOpts:
        groupBy: type
        # commitGroupsSort: title
        commitGroupsSort:
          - feat
          - fix
          - perf
          - refactor
          - style
          - ci
          - build
          - test
          - revert
          - docs
          - chore
        commitsSort: header
        # commitsSort:
        #   - scope
        #   - subject
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING

  # Create a release in Github
  - - "@semantic-release/github"
    - assets:
      - path: LICENSE.txt
        label: LICENSE
