---
# Branches from where releases can happen
branches:
  - main
  - master

# Use 'conventionalcommits' preset instead of the default 'angular'
preset: conventionalcommits

# List of plugins to use.
# Since this project is an Ansible role we won't use the npm plugin.
# Since I'm not insterested in having a dedicated CHANGELOG.md file,
# I won't be using the 'changelog' plugin to create one nor the 'git'
# plugin to commit the generated 'CHANGELOG.md' back to git
plugins:

  # Analyze that commits conform to the preset specification
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - breaking: true
          release: major
        - revert: true
          release: patch
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: docs
          release: patch
        - type: perf
          release: patch
        - type: refactor
          release: patch
        - type: revert
          release: patch
        - type: chore
          release: false
        - type: build
          release: false
        - type: ci
          release: false
        - type: test
          release: false
        - type: style
          release: false
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING

  # Generate release notes. These will be embedded in the Github release body
  - - "@semantic-release/release-notes-generator"
    - presetConfig:
        types:
          - type: feat
            section: ':sparkles: Features'
          - type: fix
            section: ':bug: Bug Fixes'
          - type: docs
            section: ':memo: Docs'
          - type: perf
            section: ':zap: Performance'
          - type: refactor
            section: ':hammer: Refactor'
          - type: revert
            section: ':poop: Revert'
          - type: chore
            section: ':eyes: Other Changes'
            hidden: false
          - type: ci
            section: ':eyes: Other Changes'
          - type: build
            section: ':eyes: Other Changes'
          - type: style
            section: ':eyes: Other Changes'
          - type: test
            section: ':eyes: Other Changes'
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING

  # Create a release in Github
  - - "@semantic-release/github"
    - assets:
      - path: LICENSE.txt
        label: LICENSE
