---
# Branches from where releases can happen
branches:
  - main
  - master

# Use 'conventionalcommits' preset instead of the default 'angular'
preset: conventionalcommits

# List of plugins to use.
# Since this project is an Ansible role we won't use the npm plugin.
# Since I'm not insterested in having a dedicated CHANGELOG.md file,
# I won't be using the 'changelog' plugin to create one nor the 'git'
# plugin to commit the generated 'CHANGELOG.md' back to git
plugins:
  # Analyze that commits conform to the preset specification
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - breaking: true
          release: major
        - revert: true
          release: patch
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: revert
          release: patch
        - type: docs
          release: false
        - type: style
          release: false
        - type: chore
          release: false
        - type: refactor
          release: patch
        - type: test
          release: false
        - type: build
          release: false
        - type: ci
          release: false
        - type: deps
          release: patch
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  # Generate release notes. These will be embedded in the Github release body
  - - "@semantic-release/release-notes-generator"
    - types:
      - type: feat
        section: ':sparkles: Features'
      - type: fix
        section: ':bug: Bug Fixes'
      - type: docs
        section: ':memo: Docs'
      - type: ci
        section: ':rocket: CI'
      - type: chore
        hidden: true
      - type: build
        section: ':hammer: Build'
        hidden: true
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  # Create a release in Github
  - - "@semantic-release/github"
    - assets:
      - path: LICENSE.txt
        label: LICENSE
