---
- name: '[debian] Execute echo command and register the output'
  command: echo {{ crossplatform_message }}
  register: result
  changed_when: false

- name: '[debian] Touch ubuntu.deleteme file (Ubuntu distro only)'
  file:
    path: /tmp/{{ ansible_distribution | lower }}.deleteme
    state: touch
    mode: 0644
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: '[debian] Touch debian.deleteme file (Debian distro only)'
  file:
    path: /tmp/{{ ansible_distribution | lower }}.deleteme
    state: touch
    mode: 0644
  changed_when: false
  when: ansible_distribution == "Debian"
