---
# tasks file

- name: '[main] Getting current OS family and distribution'
  debug:
    msg: '{{ ansible_os_family }} ({{ ansible_distribution }})'

- name: '[main] Include {{ ansible_os_family }} OS family specific variables'
  include_vars: '{{ ansible_os_family | lower }}.yml'

- name: '[main] Example of common task that runs for all platforms'
  debug:
    msg: 'This is an example task that always runs regardless of OS family and distribution'

- name: '[main] Include {{ ansible_os_family }} OS family specific tasks file'
  include_tasks: '{{ ansible_os_family | lower }}.yml'

- name: '[main] Print the output'
  debug:
    var: result.stdout
