---
# tasks file

- name: '[main] Getting current OS family and distribution'
  debug:
    msg: '{{ ansible_os_family }} ({{ ansible_distribution }})'

- name: '[main] Include {{ ansible_os_family }} OS family specific variables'
  include_vars: '{{ ansible_os_family | lower }}.yml'

- name: '[main] Example of task that runs regardless of OS family and distro'
  debug:
    msg: 'I run regardless of OS family and distro'

- name: '[main] Include {{ ansible_os_family }} OS family specific tasks file'
  include_tasks: '{{ ansible_os_family | lower }}.yml'

- name: '[main] Print the output'
  debug:
    var: result.stdout
