---
name: CD

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      #############################
      # Release to Github
      #############################

      # Since this repo follows the conventional commits specification,
      # we can use the 'semantic-release' toolset for automatic tagging/releasing
      # Instead of setting up the runner with node, then npm install semantic-release
      # and friends, and then run it with npx, we opted for a handy github action.
      # This gh action comes with some plugins pre-installed by default, but not
      # the one that provided the 'conventionalcommits' preset. Since we are not
      # interested in maintaining a dedicated CHANGELOG file in our repo, we won't
      # be installing the additional and very popular 'changelog' and 'git' extra_plugins
      # Configuration file for 'semantic-release' is '.releaserc.yml'

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #############################
      # Release to Ansible Galaxy
      #############################

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: pip3 install --no-compile ansible-base

      - name: Show Ansible version
        run: ansible --version

      - name: Release to Ansible Galaxy
        run: >-
          ansible-galaxy role import
          --api-key ${{ secrets.GALAXY_API_KEY }}
          ${GITHUB_REPOSITORY%%/*} ${GITHUB_REPOSITORY#*/}
