---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    # tags:
    #   - 'v*.*.*'
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  release:
    name: Create Ansible Galaxy release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      # Since this repo follows the conventional commit specification,
      # we will use the 'semantic-release' toolset for automatic tagging/releasing
      # Instead of setting up the runner with node, then npm install semantic-release
      # and friends, and then run it with npx, we opted for a handy github action.
      # Configuration file used for 'semantic-release' is ''.releaserc.yml'
      # NOTE: Since we are not interested in keeping a separate CHANGELOG file,
      # we are not installing the 'changelog' and 'git' extra_plugins

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: pip3 install --no-compile ansible-base

      - name: Show Ansible version
        run: ansible --version

      - name: Release to Ansible Galaxy
        run: >-
          ansible-galaxy role import
          --api-key ${{ secrets.GALAXY_API_KEY }}
          ${GITHUB_REPOSITORY%%/*} ${GITHUB_REPOSITORY#*/}

      # - name: Get the tag version
      #   id: get_version
      #   run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      # - name: Release to Github
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ steps.get_version.outputs.VERSION }}
      #     generate_release_notes: true
