---
name: Release new version

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Ansible
        run: pip3 install --no-compile ansible-base

      - name: Show Ansible version
        run: ansible --version

      - name: Create new Ansible Galaxy release
        run: >-
          ansible-galaxy role import
          --api-key ${{ secrets.GALAXY_API_KEY }}
          ${GITHUB_REPOSITORY%%/*} ${GITHUB_REPOSITORY#*/}

      - name: Create new Github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ''
          draft: false
          prerelease: false

      - name: Slack notification
        if: always()  # failure()
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          fields: all  # repo,commit,action,eventName,ref,workflow
          mention: "channel"
          if_mention: "failure"
